---
- name: Install epel repo
  command: >
     sudo
     yum
     install
     http://mirror.pnl.gov/epel/6/i386/epel-release-6-8.noarch.rpm
     -y
     creates=/etc/yum.repos.d/epel.repo

- name: Install Ansible Dependencies
  yum: >
     state=latest
     name=$item
  with_items:
     - PyYAML
     - python-paramiko
     - python-jinja2
     - python
     - git

- name: Install Ansible from github (latest dev)
  git: >
      repo=git://github.com/ansible/ansible.git
      dest=/home/vagrant/ansible

- name: add the hack env setup script to bash_profile
  template: >
          src=ansible-hack-profile.j2
          dest=/etc/profile.d/ansible.sh 
